server:
  port: 8050

security:
  authentication:
    jwt:
      # The secret should be 64 bytes (512 bits) long and must be encoded using Base64 (you can type `echo '<secret-key>' | base64` on your command line)
      # As this is the DEVELOPMENT configuration, a separate secret should be used in production, and stored securely:
      # - In a separate `application.yml` file, in the same folder as your executable WAR file
      secret: N1RnU21NM1hrbnBIN1ZMelQ5ZGJCWEp0VndIQVBoZGVtSHZiUEM1MnBXSzMzR3RuY1VOOTN0emJQWlFZRnR4cQo=
      token-validity-in-seconds: 86400 # Token is valid 24 hours
      token-validity-in-seconds-for-remember-me: 2592000 # Token is valid 30 days

logging:
  file:
    name: flightdeck.log
  level:
    # Start with only WARN messages
    root: INFO
    # Increase verbosity as needed
    com:
      desertskyrangers:
        perform: INFO
    org:
      springframework:
        security:
          web:
            csrf:
              CsrfFilter: DEBUG

spring:
  application:
    name: FlightDeck
    version: ${version}
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

#management.endpoints.web.exposure.include=*
