spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: mariadb://localhost:3306/flightlog
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
