server:
  port: 8050

logging:
  file:
    name: flightlog.log
  level:
    # Start with only WARN messages
    root: INFO
    # Increase verbosity as needed
    com:
      desertskyrangers:
        perform: INFO

spring:

  application:
    name: FlightLog
    version: ${version}

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false

  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

#management.endpoints.web.exposure.include=*
