server:
  port: 8050
  compression:
    enabled: true

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: mysql://localhost:3306/flightlog?ssl-mode=REQUIRED
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
