name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  JAVA_VERSION: "17"
  DSR_GPG_PASSWORD: ${{ secrets.DSR_GPG_PASSWORD }}
  DSR_REPO_USERNAME: ${{ secrets.DSR_REPO_USERNAME }}
  WEBSITE_DEPLOY_PATH: '/opt/dsr/flightdeck/api'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: [ 'java' ]
    steps:
      - name: Fetch sources
        uses: actions/checkout@v4

      - name: Fetch CI/CD resources
        uses: actions/checkout@v4
        with:
          repository: desertskyrangers/cicd
          path: .github

      - name: Configuration
        shell: bash
        run: |
          source .github/config.sh

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{env.JAVA_VERSION}}

      - name: Maven Repository Cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}

      - name: Build Server
        run: |
           ./gradlew clean check bootJar

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

      - name: Copy Server JAR
        run: scp -B build/libs/flightdeck-*.jar ${{env.DSR_REPO_USERNAME}}@desertskyrangers.org:/opt/dsr/store/latest/flightdeck/server.jar

#      - name: Copy Provider Icon
#        run: |
#          scp -B server/target/main/images/desertskyrangers.png ${{env.DSR_REPO_USERNAME}}@desertskyrangers.org:/opt/dsr/store/stable/desertskyrangers/provider.png
#          scp -B server/target/main/images/desertskyrangers-dark.png ${{env.DSR_REPO_USERNAME}}@desertskyrangers.org:/opt/dsr/store/stable/desertskyrangers/provider-dark.png
#          scp -B server/target/main/images/desertskyrangers-light.png ${{env.DSR_REPO_USERNAME}}@desertskyrangers.org:/opt/dsr/store/stable/desertskyrangers/provider-light.png

      - name: Update the Website
        run: ssh ${{env.DSR_REPO_USERNAME}}@desertskyrangers.org /home/ecco/bin/update-flightdeck-server
